name: Publish official release to NPM

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git
        run: |
          git config --global user.name "Simon Roberge"
          git config --global user.email "simon.roberge@vimaec.com"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm install
      - name: Bump dev version
        run: npm run bump-dev
      - name: Commit version
        run: |
          git add --all
          git commit -m 'auto versioning'
          git push
      - name: Build
        run: npm run build
      - name: Publish dev package on NPM 📦
        run: npm run publish-dev
        env:
          NODE_AUTH_TOKEN: ${{ secrets.VIM_NPM_PUSH }}
